Repository CurtinFRC/2024-Offseason, pull requests merged in 2024-07, with the labels that each got.

#61 fix: use Math.PI
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: fix

#63 [build, ci] Simplify actions, add spotbugs and refactor build
  .github/workflows/ci.yml
  build.gradle
  spotbugs-exclude.xml
  src/main/java/com/choreo/lib/Choreo.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: enhancement

#43 Add REV logging with URCL
  .styleguide
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/URCL.java
  vendordeps/URCL.json
Labels: enhancement, needs test on robot

#67 Refactor Triggers in subsystems
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: fix

#71 Log CTRE info using SignalLogger
  src/main/java/frc/robot/Robot.java
Labels: enhancement

#73 [swerve] Refactor Telemetry
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/Telemetry.java
  src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
Labels: enhancement

#74 [utils] Add deadzone function
  src/main/java/frc/robot/Utils.java
  src/test/java/frc/robot/TestUtils.java
Labels: enhancement

#75 [swerve] Better current limits
  src/main/java/frc/robot/generated/TunerConstants.java
Labels: enhancement

#76 [swerve] Apply deadzone to controller
  src/main/java/frc/robot/Robot.java
Labels: enhancement

#77 [swerve] Refactor telemetry again
  src/main/java/frc/robot/Telemetry.java
Labels: enhancement

#83 [auto] Refactor the way the Auto interface is used and add docs
  src/main/java/com/choreo/lib/Auto.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/autos/Centre2541.java
  src/main/java/frc/robot/autos/Centre26541.java
  src/main/java/frc/robot/autos/Flex.java
  src/main/java/frc/robot/autos/OneNote.java
  src/main/java/frc/robot/autos/TwoNote.java
  src/main/java/frc/robot/autos/WompWompKieran.java
Labels: enhancement

#85 Refactor main robot class to use CommandRobot
  src/main/java/edu/wpi/first/wpilibj2/command/CommandRobot.java
  src/main/java/frc/robot/Robot.java
Labels: enhancement, needs test on robot

#86 Use Java 17 switch statement in Arm
  src/main/java/frc/robot/subsystems/Arm.java
Labels: enhancement

#87 Refactor subsystem constructors to do as little as possible
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Intake.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: fix
